WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebApp/Models/User/UpdateUserWithRolesModel.cs
namespace WebApp.Models.User;

public class UpdateUserWithRolesModel
{
    public int Id { get; set; }
    public string? FullName { get; set; }
    public string? Email { get; set; }
    public string[]? Roles { get; set; }
}

WebApp/Models/Validators/Book/CreateBookModelValidator.cs
using FluentValidation;
//using WebApp.Models.Book;

//namespace WebApp.Models.Validators.Book;

//public class CreateBookModelValidator : AbstractValidator<CreateBookModel>
//{
//    public CreateBookModelValidator()
//    {
//        RuleFor(b => b.Name).NotEmpty().MinimumLength(2);
//    }
//}

WebApp/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using System.Text.Json;
using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using System.IdentityModel.Tokens.Jwt;
using WebApp.Models.Auth;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace WebApp.Controllers;
public class AuthController : Controller
{
    private readonly IHttpClientFactory _clientFactory;
    private readonly HttpClient _client;
    public AuthController(IHttpClientFactory httpClientFactory, HttpClient client)
    {
        _clientFactory = httpClientFactory;
        _client = _clientFactory.CreateClient();
    }
    public IActionResult Login()
    {
        return View(new LoginModel());
    }
    [HttpPost]
    public async Task<IActionResult> Login(LoginModel userLoginModel)
    {
        var client = _clientFactory.CreateClient();
        var content = new StringContent(JsonSerializer.Serialize(userLoginModel), Encoding.UTF8, "application/json");
        var response = await client.PostAsync("http://localhost:7700/api/Auth/Login", content);
        var jsonData = await response.Content.ReadAsStringAsync();
        var tokenModel = JsonSerializer.Deserialize<LoginResponseModel>(jsonData, new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase});

        JwtSecurityTokenHandler handler = new();
        var token = handler.ReadJwtToken(tokenModel.AccessToken);
        var claims = token.Claims.ToList();
        claims.Add(new Claim("accessToken", tokenModel.AccessToken));
        claims.Add(new Claim("refreshTokenExpire", tokenModel.RefreshTokenExpiredTime.ToString()));
        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
        return RedirectToAction("Index", "Home");
    }
    public IActionResult Register()
    {
        return View();
    }
  
    public async Task<IActionResult> Logout()
    {
        var client = _clientFactory.CreateClient();
        string email = User.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Email).Value;
        var model = new LogoutModel() { Email = email };
        var content = new StringContent(JsonSerializer.Serialize(model), Encoding.UTF8, "application/json");
        var response = await client.PostAsync("http://localhost:7700/api/Auth/Logout", content);

        await HttpContext.SignOutAsync(JwtBearerDefaults.AuthenticationScheme);
        return RedirectToAction("Index", "Home");
    }
    public async Task<IActionResult> UpdatePasswordPolicy()
    {
        return View();
    }
    public IActionResult ExcelDownload()
    {
        using (var workbook = new XLWorkbook())
        {
            var worksheet = workbook.Worksheets.Add("Users Register");

            // Başlık satırı
            worksheet.Cell(1, 1).Value = "FullName";
            worksheet.Cell(1, 2).Value = "Email";
            worksheet.Cell(1, 3).Value = "Password";
            worksheet.Cell(1, 4).Value = "PasswordConfirm";


            using (var stream = new MemoryStream())
            {
                workbook.SaveAs(stream);
                stream.Position = 0;

                // Kullanıcıya indirme olarak sunma
                return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Users.xlsx");
            }
        }
    }
    public IActionResult ExcelUpload()
    {
        return View();
    }
}

WebApp/Controllers/AuthorsController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace WebApp.Controllers;
public class AuthorsController : Controller
{
    public override void OnActionExecuting(ActionExecutingContext context)
    {
        ViewData["Token"] = User?.Claims?.FirstOrDefault(x => x.Type == "accessToken")?.Value;
        base.OnActionExecuting(context);
    }

    public IActionResult ExcelDownload()
    {
        using (var workbook = new XLWorkbook())
        {
            var worksheet = workbook.Worksheets.Add("Authors");

            // Başlık satırı
            worksheet.Cell(1, 1).Value = "Name";

            using (var stream = new MemoryStream())
            {
                workbook.SaveAs(stream);
                stream.Position = 0;

                // Kullanıcıya indirme olarak sunma
                return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Authors.xlsx");
            }
        }
    }
    public IActionResult ExcelUpload()
    {
        return View();
    }
    public async Task<IActionResult> GetList()
    { 
        return View();
    }
    public async Task<IActionResult> GetById(int id)
    {
        return View(id);
    }
    public async Task<IActionResult> Create()
    {
        return View();
    }
    public async Task<IActionResult> Update(int id)
    {
        return View(id);
    }
    public async Task<IActionResult> Delete(int id)
    {
        return View(id);
    }
}

WebApp/Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace WebApp.Controllers;
[Authorize]
public class BooksController : Controller
{
    public override void OnActionExecuting(ActionExecutingContext context)
    {
        ViewData["Token"] = User?.Claims?.FirstOrDefault(x => x.Type == "accessToken")?.Value;
        base.OnActionExecuting(context);
    }
    public async Task<IActionResult> GetList()
    {
        return View();
    }
    public async Task<IActionResult> GetById(int id)
    {
        return View(id);
    }
    public async Task<IActionResult> Create()
    {

        return View();
    }

    public async Task<IActionResult> Update(int id)
    {
        return View(id);
    }
    public async Task<IActionResult> Delete(int id)
    {

        return View(id);
    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Diagnostics;
using WebApp.Models;

namespace WebApp.Controllers;
public class HomeController : Controller
{
    public override void OnActionExecuting(ActionExecutingContext context)
    {
        ViewData["Token"] = User?.Claims?.FirstOrDefault(x => x.Type == "accessToken")?.Value;
        base.OnActionExecuting(context);
    }
    public IActionResult Index()
    {
        return View();
    }
    public IActionResult Add()
    {
        return View();
    }
    public string AdminPage()
    {
        return "admin page";
    }
    public string UserPage()
    {
        return "user page";
    }
}

WebApp/Controllers/UsersController.cs
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using WebApp.Models.User;

namespace WebApp.Controllers;
public class UsersController : Controller
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    public UsersController(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }
    public override void OnActionExecuting(ActionExecutingContext context)
    {
        ViewData["Token"] = _httpContextAccessor.HttpContext?.User?.Claims?.FirstOrDefault(x => x.Type == "accessToken")?.Value;
        base.OnActionExecuting(context);
    }
    public async Task<IActionResult> GetList()
    {
        return View();
    }
    public async Task<IActionResult> UpdateUserWithRoles(int id)
    {
        return View(id);
    }
}

WebApp/Views/Authors/Create.cshtml
@{ Layout = "_ModalLayout"; }

<div class="container">
    <form id="createAuthorForm" class="w-100 m-10 p-3 shadow mx-auto" method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label for="Name" class="form-label">Name:</label>
            <input type="text" class="form-control" id="Name"/>
        </div>
        <div class="mb-3">
            <label for="ImageUrl" class="form-label">ImageUrl:</label>
            <input type="file" class="form-control" id="ImageUrl" name="ImageUrl" />
        </div>
        <div class="mb-3">
            <button type="button" class="btn btn-primary w-100" id="saveButton">Save</button>
        </div>
    </form>
</div>

@section Scripts {
    <script>
        $(function () {
            $('#saveButton').click(function () {
                var formData = new FormData();
                formData.append('Name', $('#Name').val());
                formData.append('ImageUrl', $('#ImageUrl')[0].files[0]);

                $.ajax({
                    url: baseUrl + 'api/Authors/Add',
                    type: 'POST',
                    headers: {
                        'Authorization': 'Bearer @ViewData["Token"]'
                    },
                    processData: false,
                    contentType: false,
                    data: formData,
                    success: function (response) {
                        Swal.fire({
                            title: 'Success!',
                            text: 'Yazar başarıyla eklendi!',
                            icon: 'success',
                            confirmButtonText: 'OK'
                        }).then((result) => {
                            if (result.isConfirmed) {
                                window.location.href = '@Url.Action("GetList", "Authors")';
                            }
                        });
                    },
                    error: function (xhr, status, error) {
                        var errorMessage;
                        if (xhr.status === 401) {
                            errorMessage = 'Yetkilendirme hatası! Lütfen giriş yapın.';
                        } else {
                            errorMessage = xhr.responseJSON ? xhr.responseJSON.message : 'Yazar eklenirken bir hata oluştu.';
                        }

                        Swal.fire({
                            title: 'Error!',
                            text: errorMessage,
                            icon: 'error',
                            confirmButtonText: 'OK'
                        });
                    }
                });
            });
        });
    </script>
}

WebApp/Views/Books/Create.cshtml
@{ Layout = "_ModalLayout"; }

<div class="container">
    <form id="createBookForm" class="w-100 m-10 p-3 shadow mx-auto" method="post">
        <div class="mb-3">
            <label for="Name" class="form-label">Name:</label>
            <input type="text" class="form-control" name="Name" id="Name" />
        </div>
        <div class="mb-3">
            <label for="AuthorId" class="form-label">AuthorId:</label>
            <input type="text" class="form-control" name="AuthorId" id="AuthorId" />
        </div>
        <div class="mb-3">
            <label for="ImageUrl" class="form-label">Image:</label>
            <input type="file" class="form-control" id="ImageUrl" name="ImageUrl" />
        </div>
        <div class="mb-3">
            <button type="button" class="btn btn-primary w-100" id="saveButton">Save</button>
        </div>
    </form>
</div>

@section Scripts {
    <script>
        $(function () {
            $('#saveButton').click(function () {
                var formData = new FormData();
                formData.append('Name', $('#Name').val());
                formData.append('AuthorId', $('#AuthorId').val());
                formData.append('ImageUrl', $('#ImageUrl')[0].files[0]);
              
                $.ajax({
                    url: baseUrl + 'api/Books/Add',
                    type: 'POST',
                    headers: {
                        'Authorization': 'Bearer @ViewData["Token"]'
                    },
                    processData: false,
                    contentType: false,
                    data: formData,
                    success: function (response) {
                        Swal.fire({
                            title: 'Success!',
                            text: 'Kitap başarıyla eklendi la!',
                            icon: 'success',
                            confirmButtonText: 'OK'
                        }).then((result) => {
                            if (result.isConfirmed) {
                                window.location.href = '@Url.Action("GetList", "Books")';
                            }
                        });
                    },
                    error: function (xhr, status, error) {
                        var errorMessage;
                        if (xhr.status === 401) {
                            errorMessage = 'Yetkilendirme hatası! Lütfen giriş yapın.';
                        } else {
                            errorMessage = xhr.responseJSON ? xhr.responseJSON.message : 'Yazar eklenirken bir hata oluştu.';
                        }

                        Swal.fire({
                            title: 'Error!',
                            text: errorMessage,
                            icon: 'error',
                            confirmButtonText: 'OK'
                        });
                    }
                });
            });
        });
    </script>
}

WebApp/Views/Books/Delete.cshtml
@model int

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $(function () {
            $.ajax({
                url: baseUrl + 'api/Books/@Model',
                type: 'DELETE',
                headers: {
                    'Authorization': 'Bearer @ViewData["Token"]'
                },
                success: function (response) {
                    Swal.fire({
                        title: 'Success!',
                        text: 'getti',
                        icon: 'success',
                        confirmButtonText: 'OK'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            window.location.href = '@Url.Action("GetList", "Books")';
                        }
                    });
                },
                error: function (xhr, status, error) {
                    var errorMessage;
                    if (xhr.status === 401) {
                        errorMessage = 'Yetkilendirme hatası! Lütfen giriş yapın.';
                    } else {
                        errorMessage = xhr.responseJSON ? xhr.responseJSON.message : 'Yazar eklenirken bir hata oluştu.';
                    }

                    Swal.fire({
                        title: 'Error!',
                        text: errorMessage,
                        icon: 'error',
                        confirmButtonText: 'OK'
                    });
                }
            });
        });
    </script>
}

WebApp/Views/Books/GetList.cshtml
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" />

<a class="btn btn-danger btn-sm" id="openCreateModal">Create</a>

<table id="bookTable" class="display">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Author Name</th>
            <th>Actions</th>
        </tr>
    </thead>
</table>

<div class="modal fade" id="createBookModal" tabindex="-1" aria-labelledby="createBookModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createBookModalLabel">Create Book</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modalContent">
                <!-- Modal içeriği AJAX ile doldurulacak -->
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="updateBookModal" tabindex="-1" aria-labelledby="updateBookModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateBookModalLabel">Update Book</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modalContentUpdate">
                <!-- Modal içeriği AJAX ile doldurulacak -->
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(function () {
            $('#bookTable').DataTable({
                "language": {
                    "url": 'https://cdn.datatables.net/plug-ins/2.0.8/i18n/tr.json',
                },
                "paging": true,
                "pageLength": 10,
                "lengthMenu": [5, 10, 25, 50, 100],
                "columns": [
                    { "data": "id" },
                    {
                        "data": "name",
                        "render": function (data, type, row) {
                            return `<a href="/Books/GetById/${row.id}" data-toggle="tooltip" title="ID: ${row.id}, Name: ${data} AuthorName: ${row.authorName}">${data}</a>`;
                        }
                    },
                    { "data": "authorName" },
                    {
                        "data": null,
                        "render": function (data, type, row) {
                            return `<a class="btn btn-danger btn-sm" href="/Books/Delete/${row.id}">Delete</a>
                                     <a class="btn btn-warning btn-sm openUpdateModal" data-id="${row.id}">Update</a>`;
                        }
                    }
                ],
                "ajax": {
                    "url": baseUrl + 'api/Books/GetList',
                    "type": "GET",
                    "headers": {
                        'Authorization': 'Bearer @ViewData["Token"]'
                    },
                    "dataType": "json",
                    "dataSrc": "",
                    "error": function (xhr, status, error) {
                        if (xhr.status === 401) {
                            Swal.fire({
                                title: 'Yetkisiz Erişim!',
                                text: 'Bu işlemi gerçekleştirmek için giriş yapmalısınız.',
                                icon: 'warning',
                                confirmButtonText: 'Anladım'
                            }).then(() => {
                                window.location.href = '/Auth/Login'; // Kullanıcıyı giriş sayfasına yönlendir
                            });
                        } else {
                            Swal.fire({
                                title: 'Hata!',
                                text: 'Bir hata oluştu. Lütfen tekrar deneyin.',
                                icon: 'error',
                                confirmButtonText: 'Tamam'
                            });
                        }
                    }
                },
                "filter": true,
                "dom": 'Bfrtip',
                "buttons": [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]               
            });
            // Tooltip initialization
            $(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });

            $('#openCreateModal').click(function () {
                $.get('@Url.Action("Create", "Books")')
                    .done(function (data) {
                        $('#modalContent').html(data);
                        $('#createBookModal').modal('show');
                    })
                    .fail(function () {
                        Swal.fire({
                            title: 'Error!',
                            text: 'An error occurred while loading the create book page.',
                            icon: 'error',
                            confirmButtonText: 'OK'
                        });
                    });
            });

            $(document).on('click', '.openUpdateModal', function () {
                var bookId = $(this).data('id');
                $.get('@Url.Action("Update", "Books")', { id: bookId })
                    .done(function (data) {
                        $('#modalContentUpdate').html(data);
                        $('#updateBookModal').modal('show');
                    })
                    .fail(function () {
                        Swal.fire({
                            title: 'Error!',
                            text: 'An error occurred while loading the update book page.',
                            icon: 'error',
                            confirmButtonText: 'OK'
                        });
                    });
            });
        });
    </script>
}

WebApp/Views/Books/Update.cshtml
@model int

@{
    Layout = "_ModalLayout";
}

<form id="updateBookForm" class="w-120 p-3 shadow mx-auto" method="post" enctype="multipart/form-data">
    <input type="hidden" name="Id" id="Id" value="@Model" />
    <div class="mb-3">
        <label for="Name" class="form-label">Name:</label>
        <input type="text" class="form-control" id="Name" name="Name" />
    </div>
    <div class="mb-3">
        <label for="AuthorId" class="form-label">AuthorId:</label>
        <input type="text" class="form-control" id="AuthorId" name="AuthorId" />
    </div>
    <div class="mb-3">
        <label for="ImageUrl" class="form-label">Image URL:</label>
        <input type="file" class="form-control" id="ImageUrl" name="ImageUrl" />
    </div>
    <div class="mb-3">
        <button type="button" class="btn btn-primary w-100" id="updateButton">Update</button>
    </div>
</form>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $(function () {
            // Form doldurma işlemi
            $.ajax({
                url: baseUrl + 'api/Books/' + @Model,
                type: 'GET',
                headers: {
                    'Authorization': 'Bearer @ViewData["Token"]'
                },
                success: function (data) {
                    $('#Name').val(data.name);
                    $('#AuthorId').val(data.authorId);
                    $('#ImageUrl').val(data.imageUrl);
                },
                error: function (xhr, status, error) {
                    var errorMessage;
                    if (xhr.status === 401) {
                        errorMessage = 'Yetkilendirme hatası! Lütfen giriş yapın.';
                    } else {
                        errorMessage = xhr.responseJSON ? xhr.responseJSON.message : 'Bir hata oluştu.';
                    }

                    Swal.fire({
                        title: 'Error!',
                        text: errorMessage,
                        icon: 'error',
                        confirmButtonText: 'OK'
                    });
                }
            });

            // Güncelleme işlemi
            $('#updateButton').click(function () {
                var formData = new FormData();
                formData.append('Id', $('#Id').val());
                formData.append('Name', $('#Name').val());
                formData.append('AuthorId', $('#AuthorId').val());
                formData.append('ImageUrl', $('#ImageUrl')[0].files[0]);

                $.ajax({
                    url: baseUrl + 'api/Books/Update',
                    type: 'PUT',
                    headers: {
                        'Authorization': 'Bearer @ViewData["Token"]'
                    },
                    processData: false,
                    contentType: false,
                    data: formData,
                    success: function (response) {
                        Swal.fire({
                            title: 'Success!',
                            text: 'Kitap başarıyla güncellendi.',
                            icon: 'success',
                            confirmButtonText: 'OK'
                        }).then((result) => {
                            if (result.isConfirmed) {
                                window.location.href = '@Url.Action("GetList", "Books")';
                            }
                        });
                    },
                    error: function (xhr, status, error) {
                        var errorMessage;
                        if (xhr.status === 401) {
                            errorMessage = 'Yetkilendirme hatası! Lütfen giriş yapın.';
                        } else {
                            errorMessage = xhr.responseJSON ? xhr.responseJSON.message : 'Kitap güncellenirken bir hata oluştu.';
                        }

                        Swal.fire({
                            title: 'Error!',
                            text: errorMessage,
                            icon: 'error',
                            confirmButtonText: 'OK'
                        });
                    }
                });
            });
        });
    </script>
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.9/dist/sweetalert2.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css">


</head>
<body style="background-image: url('/images/plain-white-background-xdwiksazlsuzkuhi.jpg');">
    <header>
        <nav style="background-color:cadetblue" class="navbar navbar-expand-sm border-bottom" @* class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" *@>
            <div style="background-color:mediumaquamarine" class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Add">AddTogether</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="GetList">Book List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="GetList">Author List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="GetList">User List</a>
                        </li>
                        <li class="nav-item ms-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()


        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.2/umd/popper.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>
    <script>var baseUrl = 'http://localhost:7700/';</script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>